# Scikit-learn

In [1]:
import pandas as pd
import numpy as np
import time
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

In [2]:
df_loan = pd.read_csv("/home/huzaifa/Desktop/my_ml_project/data/loan_data_new.csv")

In [3]:
df_loan

,Age,Gender,Education,Person Income,Employee Experience,Home Onwership,Loan Amount,Loan Intent,Loan interest Rate,Loan percentage,Credit History,Credit Score,Previous Loan,Loan Status
0,22,female,Master,71948,0,RENT,35000,PERSONAL,16.02,0.49,3,561,No,1
1,21,female,High School,12282,0,OWN,1000,EDUCATION,11.14,0.08,2,504,Yes,0
2,25,female,High School,12438,3,MORTGAGE,5500,MEDICAL,12.87,0.44,3,635,No,1
3,23,female,Bachelor,79753,0,RENT,35000,MEDICAL,15.23,0.44,2,675,No,1
4,24,male,Master,66135,1,RENT,35000,MEDICAL,14.27,0.53,4,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27,male,Associate,47971,6,RENT,15000,MEDICAL,15.66,0.31,3,645,No,1
44996,37,female,Associate,65800,17,RENT,9000,HOMEIMPROVEMENT,14.07,0.14,11,621,No,1
44997,33,male,Associate,56942,7,RENT,2771,DEBTCONSOLIDATION,10.02,0.05,10,668,No,1
44998,29,male,Bachelor,33164,4,RENT,12000,EDUCATION,13.23,0.36,6,604,No,1
44999,24,male,High School,51609,1,RENT,6665,DEBTCONSOLIDATION,17.05,0.13,3,628,No,1

In [4]:
df_loan = df_loan.dropna() # no null values (na) found
df_loan

,Age,Gender,Education,Person Income,Employee Experience,Home Onwership,Loan Amount,Loan Intent,Loan interest Rate,Loan percentage,Credit History,Credit Score,Previous Loan,Loan Status
0,22,female,Master,71948,0,RENT,35000,PERSONAL,16.02,0.49,3,561,No,1
1,21,female,High School,12282,0,OWN,1000,EDUCATION,11.14,0.08,2,504,Yes,0
2,25,female,High School,12438,3,MORTGAGE,5500,MEDICAL,12.87,0.44,3,635,No,1
3,23,female,Bachelor,79753,0,RENT,35000,MEDICAL,15.23,0.44,2,675,No,1
4,24,male,Master,66135,1,RENT,35000,MEDICAL,14.27,0.53,4,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27,male,Associate,47971,6,RENT,15000,MEDICAL,15.66,0.31,3,645,No,1
44996,37,female,Associate,65800,17,RENT,9000,HOMEIMPROVEMENT,14.07,0.14,11,621,No,1
44997,33,male,Associate,56942,7,RENT,2771,DEBTCONSOLIDATION,10.02,0.05,10,668,No,1
44998,29,male,Bachelor,33164,4,RENT,12000,EDUCATION,13.23,0.36,6,604,No,1
44999,24,male,High School,51609,1,RENT,6665,DEBTCONSOLIDATION,17.05,0.13,3,628,No,1

In [5]:
df_loan.columns

Index(['Age', 'Gender', 'Education', 'Person Income', 'Employee Experience',
       'Home Onwership', 'Loan Amount', 'Loan Intent', 'Loan interest Rate',
       'Loan percentage', 'Credit History', 'Credit Score', 'Previous Loan',
       'Loan Status'],
      dtype='str')

In [6]:
df_loan= pd.get_dummies(df_loan, drop_first=True)
df_loan

,Age,Person Income,Employee Experience,Loan Amount,Loan interest Rate,Loan percentage,Credit History,Credit Score,Loan Status,Gender_male,...,Education_Master,Home Onwership_OTHER,Home Onwership_OWN,Home Onwership_RENT,Loan Intent_EDUCATION,Loan Intent_HOMEIMPROVEMENT,Loan Intent_MEDICAL,Loan Intent_PERSONAL,Loan Intent_VENTURE,Previous Loan_Yes
0,22,71948,0,35000,16.02,0.49,3,561,1,False,...,True,False,False,True,False,False,False,True,False,False
1,21,12282,0,1000,11.14,0.08,2,504,0,False,...,False,False,True,False,True,False,False,False,False,True
2,25,12438,3,5500,12.87,0.44,3,635,1,False,...,False,False,False,False,False,False,True,False,False,False
3,23,79753,0,35000,15.23,0.44,2,675,1,False,...,False,False,False,True,False,False,True,False,False,False
4,24,66135,1,35000,14.27,0.53,4,586,1,True,...,True,False,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27,47971,6,15000,15.66,0.31,3,645,1,True,...,False,False,False,True,False,False,True,False,False,False
44996,37,65800,17,9000,14.07,0.14,11,621,1,False,...,False,False,False,True,False,True,False,False,False,False
44997,33,56942,7,2771,10.02,0.05,10,668,1,True,...,False,False,False,True,False,False,False,False,False,False
44998,29,33164,4,12000,13.23,0.36,6,604,1,True,...,False,False,False,True,True,False,False,False,False,False
44999,24,51609,1,6665,17.05,0.13,3,628,1,True,...,False,False,False,True,False,False,False,False,False,False

In [7]:
df_loan.columns

Index(['Age', 'Person Income', 'Employee Experience', 'Loan Amount',
       'Loan interest Rate', 'Loan percentage', 'Credit History',
       'Credit Score', 'Loan Status', 'Gender_male', 'Education_Bachelor',
       'Education_Doctorate', 'Education_High School', 'Education_Master',
       'Home Onwership_OTHER', 'Home Onwership_OWN', 'Home Onwership_RENT',
       'Loan Intent_EDUCATION', 'Loan Intent_HOMEIMPROVEMENT',
       'Loan Intent_MEDICAL', 'Loan Intent_PERSONAL', 'Loan Intent_VENTURE',
       'Previous Loan_Yes'],
      dtype='str')

In [8]:
y = df_loan["Loan Status"].values
X = df_loan.drop(columns=["Loan Status"]).values

In [9]:
X_train_loan, X_test_loan, y_train_loan, y_test_loan = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_loan = scaler.fit_transform(X_train_loan)
X_test_loan = scaler.transform(X_test_loan)

In [10]:
model_loan = LogisticRegression(max_iter=1000)
model_loan.fit(X_train_loan, y_train_loan)

LogisticRegression(max_iter=1000)

In [11]:
y_pred = model_loan.predict(X_test_loan)

In [12]:
from sklearn.metrics import r2_score, mean_squared_error, confusion_matrix

In [13]:
import time 
import tracemalloc

tracemalloc.start()
start = time.perf_counter()
model_loan.fit(X_train_loan, y_train_loan)
train_time_sklearn = time.perf_counter() - start
_, peak_mem_sklearn = tracemalloc.get_traced_memory()
tracemalloc.stop()

In [14]:
start = time.perf_counter()
y_pred_sklearn = model_loan.predict(X_test_loan)
predict_time_sklearn = time.perf_counter() - start

In [15]:
rmse_sklearn = np.sqrt(mean_squared_error(y_test_loan, y_pred))
r2_sklearn = r2_score(y_test_loan, y_pred)

In [16]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

In [17]:
print("Scikit-learn Loan Dataset")
print("F1 Score:", f1_score(y_test_loan, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test_loan, y_pred))
print("Accuracy:", accuracy_score(y_test_loan, y_pred))
print(f"Train time: {train_time_sklearn:.4f}s")
print(f"Predict time: {predict_time_sklearn:.4f}s")
print(f"Peak memory: {peak_mem_sklearn / (1024**2):.2f} MB")

Scikit-learn Loan Dataset
F1 Score: 0.7586382113821138
Confusion Matrix:
 [[6557  433]
 [ 517 1493]]
Accuracy: 0.8944444444444445
Train time: 0.1587s
Predict time: 0.0009s
Peak memory: 2.17 MB

# Using Tensorflow

In [18]:
import tensorflow as tf
from tensorflow.keras import layers, models

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1785165342.957037   17327 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [19]:
model_tf_loan = models.Sequential([
    layers.Input(shape=(X_train_loan.shape[1],)),
    layers.Dense(1, activation="sigmoid")   # sigmoid = logistic regression
])

E0000 00:00:1785165344.570769   17327 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
I0000 00:00:1785165344.570798   17327 cuda_diagnostics.cc:160] env: CUDA_VISIBLE_DEVICES="-1"
I0000 00:00:1785165344.570808   17327 cuda_diagnostics.cc:163] CUDA_VISIBLE_DEVICES is set to -1 - this hides all GPUs from CUDA
I0000 00:00:1785165344.570816   17327 cuda_diagnostics.cc:171] verbose logging is disabled. Rerun with verbose logging (usually --v=1 or --vmodule=cuda_diagnostics=1) to get more diagnostic output from this module
I0000 00:00:1785165344.570819   17327 cuda_diagnostics.cc:176] retrieving CUDA diagnostic information for host: shahnoor-B550M-AORUS-ELITE
I0000 00:00:1785165344.570823   17327 cuda_diagnostics.cc:183] hostname: shahnoor-B550M-AORUS-ELITE
I0000 00:00:1785165344.570901   17327 cuda_diagnostics.cc:190] libcuda reported version is: 595.71.5
I0000 00:00:1785165344.570920   17327 cuda_diagnostics.cc:194] kernel reported version is: 595.71.5
I0000 00:00:1785165344.570922   17327 cuda_diagnostics.cc:284] kernel version seems to match DSO: 595.71.5

In [20]:
model_tf_loan.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [21]:
tracemalloc.start()
start = time.perf_counter()
model_tf_loan.fit(X_train_loan, y_train_loan, epochs=50, batch_size=32, verbose=0)
train_time_tf_loan = time.perf_counter() - start
_, peak_mem_tf_loan = tracemalloc.get_traced_memory()
tracemalloc.stop()

In [22]:
start = time.perf_counter()
y_pred_prob_tf_loan = model_tf_loan.predict(X_test_loan, verbose=0).flatten()
predict_time_tf_loan = time.perf_counter() - start

In [23]:
y_pred_tf_loan = (y_pred_prob_tf_loan > 0.5).astype(int)
acc_tf_loan = accuracy_score(y_test_loan, y_pred_tf_loan)
f1_tf_loan = f1_score(y_test_loan, y_pred_tf_loan)
print("Tensorflow Loan Dataset")
print(f"Acc: {acc_tf_loan:.4f}")
print(f"F1: {f1_tf_loan:.4f}")
print(f"Train: {train_time_tf_loan:.4f}s")
print(f"Predict: {predict_time_tf_loan:.4f}s")
print(f"Mem: {peak_mem_tf_loan/(1024**2):.2f}MB")

Tensorflow Loan Dataset
Acc: 0.8951
F1: 0.7593
Train: 78.4495s
Predict: 0.2633s
Mem: 9.13MB

# Pytorch

In [24]:
"""import torch
import torch.nn as nn"""

'import torch\nimport torch.nn as nn'

In [25]:
"""X_train_loan_t = torch.tensor(X_train_loan, dtype=torch.float32)
y_train_loan_t = torch.tensor(y_train_loan, dtype=torch.float32).view(-1, 1)
X_test_loan_t = torch.tensor(X_test_loan, dtype=torch.float32)"""

'X_train_loan_t = torch.tensor(X_train_loan, dtype=torch.float32)\ny_train_loan_t = torch.tensor(y_train_loan, dtype=torch.float32).view(-1, 1)\nX_test_loan_t = torch.tensor(X_test_loan, dtype=torch.float32)'

In [26]:
"""model_torch_loan = nn.Linear(X_train_loan.shape[1], 1)
criterion_loan = nn.BCEWithLogitsLoss()   # sigmoid built into the loss
optimizer_loan = torch.optim.Adam(model_torch_loan.parameters(), lr=0.01)"""

'model_torch_loan = nn.Linear(X_train_loan.shape[1], 1)\ncriterion_loan = nn.BCEWithLogitsLoss()   # sigmoid built into the loss\noptimizer_loan = torch.optim.Adam(model_torch_loan.parameters(), lr=0.01)'

In [27]:
"""tracemalloc.start()
start = time.perf_counter()
for epoch in range(50):
    optimizer_loan.zero_grad()
    outputs = model_torch_loan(X_train_loan_t)
    loss = criterion_loan(outputs, y_train_loan_t)
    loss.backward()
    optimizer_loan.step()
train_time_torch_loan = time.perf_counter() - start
_, peak_mem_torch_loan = tracemalloc.get_traced_memory()
tracemalloc.stop()"""

'tracemalloc.start()\nstart = time.perf_counter()\nfor epoch in range(50):\n    optimizer_loan.zero_grad()\n    outputs = model_torch_loan(X_train_loan_t)\n    loss = criterion_loan(outputs, y_train_loan_t)\n    loss.backward()\n    optimizer_loan.step()\ntrain_time_torch_loan = time.perf_counter() - start\n_, peak_mem_torch_loan = tracemalloc.get_traced_memory()\ntracemalloc.stop()'

In [28]:
"""model_torch_loan.eval()
start = time.perf_counter()
with torch.no_grad():
    y_pred_logits_loan = model_torch_loan(X_test_loan_t).numpy().flatten()
predict_time_torch_loan = time.perf_counter() - start"""

'model_torch_loan.eval()\nstart = time.perf_counter()\nwith torch.no_grad():\n    y_pred_logits_loan = model_torch_loan(X_test_loan_t).numpy().flatten()\npredict_time_torch_loan = time.perf_counter() - start'

In [29]:
"""y_pred_torch_loan = (1 / (1 + np.exp(-y_pred_logits_loan)) > 0.5).astype(int)
acc_torch_loan = accuracy_score(y_test_loan, y_pred_torch_loan)
f1_torch_loan = f1_score(y_test_loan, y_pred_torch_loan)
print(f"[Torch-Loan] Acc: {acc_torch_loan:.4f}, F1: {f1_torch_loan:.4f}, Train: {train_time_torch_loan:.4f}s, Predict: {predict_time_torch_loan:.4f}s, Mem: {peak_mem_torch_loan/(1024**2):.2f}MB")"""

'y_pred_torch_loan = (1 / (1 + np.exp(-y_pred_logits_loan)) > 0.5).astype(int)\nacc_torch_loan = accuracy_score(y_test_loan, y_pred_torch_loan)\nf1_torch_loan = f1_score(y_test_loan, y_pred_torch_loan)\nprint(f"[Torch-Loan] Acc: {acc_torch_loan:.4f}, F1: {f1_torch_loan:.4f}, Train: {train_time_torch_loan:.4f}s, Predict: {predict_time_torch_loan:.4f}s, Mem: {peak_mem_torch_loan/(1024**2):.2f}MB")'